Us3 feedback v2
Viestinta/viestinta pull request #22
Opened 2017-03-16 10:12 UTC by teatimes

Made database tests, changed some components and added new functions.

2017-03-17 16:59 UTC, weedle1912 commented on src/client/components/Message.js
> -Message.propTypes = {
This line is needed. "Message.propTypes", not just "propTypes", for anything to render in browser.

2017-03-17 17:04 UTC, weedle1912 requested changes
Errors when using UI to send message:
- Unhandled rejection SequelizeDatabaseError: column Feedback.lectureId does not exist
- Unhandled rejection SequelizeDatabaseError: column "messageId" does not exist
- Unhandled rejection TypeError: result.setLecture is not a function

2017-03-19 18:56 UTC, teatimes reviewed
Fixed requested changes

2017-03-19 19:55 UTC, weedle1912 requested changes
1) When connected to database:
- postgres_1| ERROR:  column "userId" does not exist at character 80
- viestinta_node| Unhandled rejection SequelizeDatabaseError: column "userId" does not exist

2) When sending messages in UI:
- postgres_1| ERROR:  column "lectureId" of relation "Messages" does not exist at character 23
- viestinta_node| Unhandled rejection SequelizeDatabaseError: column "lectureId" of relation "Messages" does not exist

Everything else is OK. These errors are only visible in terminal.

2017-03-21 13:43 UTC, odgaard commented
Approved, even though it decreases the code coverage from 98.66% to 93.85%.  Tested on my Ubuntu laptop and Drone.

2017-03-21 13:48 UTC, merged