Issues
Viestinta/viestinta pull request #67
Opened 2017-04-14 13:39 UTC by teatimes

Fixed some issues.

2017-04-15 10:07 UTC, odgaard requested changes
All tests pass, everything is functional on the website.

2017-04-15 10:07 UTC, odgaard commented on src/client/components/FeedbackMenu.js
> +var MIN = 6000*60
Expect this is supposed to be 1000*60?

2017-04-15 10:07 UTC, odgaard commented on src/client/components/LectureTable.js
> +        console.log(new Date())
What is this used for?

2017-04-15 10:07 UTC, odgaard commented on src/client/components/ChatBox.js
> +  validateMessage (msg) {
The error message overflows when the message box has 2 lines or more of text:
![image](https://cloud.githubusercontent.com/assets/23553119/25062777/9e8efee4-21cb-11e7-89ae-29b06b17450f.png)

2017-04-16 13:12 UTC, teatimes commented on src/client/components/FeedbackMenu.js
> +var MIN = 6000*60
FIxed now

2017-04-16 13:12 UTC, teatimes commented on src/client/components/LectureTable.js
> +        console.log(new Date())
Used it to see where the wrong date came from. Removed now

2017-04-17 19:12 UTC, weedle1912 reviewed
The changes done under commit "Sending message when pushing enter" makes it possible to send empty message, as well as leaving a newline '\n' in the input field.

2017-04-18 13:18 UTC, odgaard approved these changes

2017-04-18 13:20 UTC, merged